using Sim.Core;
using Sim.Evac;
using Xunit;
using Xunit.Abstractions;

namespace Sim.ParityTests;

// PANIC-EVAC.md §8 done-condition (headless form): on a hand-built tiny grid, the full transition
// PLAYS ONCE — organized cars, a central incident, panic + flee, gridlock, driver→pedestrian
// conversion, and a foot-exodus that respects the known-world hard edge and drains toward the safe
// radius. These are BEHAVIOURAL/PROPERTY assertions on the evac layer (parity-exempt), not golden
// comparisons. The determinism hash of the driving core is guarded separately (Sim.Bench); here we
// additionally prove the EVAC RUN itself is deterministic and that no pedestrian ever leaves the mesh
// (the ORCA wall-winding invariant).
//
// Fixture: scenarios/evac-grid/net.net.xml — a 4x4 priority-junction grid (nodes at {60,140,220,300})
// with boundary stubs, generated by netgenerate (parity-exempt; no golden). Vehicles are spawned at
// runtime, so the test needs no rou.xml demand and no SUMO.
public class EvacSpineTests
{
    private readonly ITestOutputHelper _out;
    public EvacSpineTests(ITestOutputHelper output) => _out = output;

    private static readonly string NetPath =
        Path.Combine(RepoRoot(), "scenarios", "evac-grid", "net.net.xml");

    private const double StepLength = 1.0;

    // Straight-across routes: each boundary entry funnels to the opposite exit, so horizontal and
    // vertical flows cross at every junction (yield → congestion under panic). Deterministic order.
    private static readonly (string From, string To)[] Routes =
    {
        ("left0A0", "D0right0"), ("left1A1", "D1right1"), ("left2A2", "D2right2"), ("left3A3", "D3right3"),
        ("right0D0", "A0left0"), ("right1D1", "A1left1"), ("right2D2", "A2left2"), ("right3D3", "A3left3"),
        ("bottom0A0", "A3top0"), ("bottom1B0", "B3top1"), ("bottom2C0", "C3top2"), ("bottom3D0", "D3top3"),
        ("top0A3", "A0bottom0"), ("top1B3", "B0bottom1"), ("top2C3", "C0bottom2"), ("top3D3", "D0bottom3"),
    };

    private static EvacConfig Config() => new()
    {
        // Central incident covers the inner grid; corners fall just outside.
        ThetaPanic = 0.05,
        VicinityWidth = 8.0,
        BlockedDwellSeconds = 3.0,
        SafeRadius = 120.0,
        PedMaxSpeed = 3.0,
        ExitEdges = new[]
        {
            "A0bottom0", "A0left0", "A1left1", "A2left2", "A3left3", "A3top0",
            "B0bottom1", "B3top1", "C0bottom2", "C3top2",
            "D0bottom3", "D0right0", "D1right1", "D2right2", "D3right3", "D3top3",
        },
    };

    private static readonly Incident TheIncident = new(X: 180.0, Y: 180.0, StartTime: 8.0, Radius: 140.0);

    // Build a fresh engine + director on the grid, spawn the organized traffic, and track it.
    private static (Engine Engine, EvacDirector Director, List<VehicleHandle> Handles) Build()
    {
        var engine = new Engine();
        engine.LoadNetwork(NetPath);   // deterministic default config: 1s Euler, sigma 0

        var vtype = engine.DefineVType(new VTypeParams { VClass = "passenger", Sigma = 0.0 });
        var net = Sim.Ingest.NetworkParser.Parse(NetPath);
        var director = new EvacDirector(engine, net, TheIncident, Config(), StepLength);

        var handles = new List<VehicleHandle>();
        foreach (var (from, to) in Routes)
        {
            foreach (var pos in new[] { 5.0, 45.0 })
            {
                var h = engine.SpawnVehicle(vtype, from, to, departPos: pos);
                director.Track(h);
                handles.Add(h);
            }
        }

        return (engine, director, handles);
    }

    // The whole cascade: incident → panic → flee → gridlock → conversion → contained foot-exodus.
    [Fact]
    public void Grid_IncidentTriggersPanicFleeBlockConvertAndFootExodus()
    {
        var (_, director, _) = Build();

        var maxPedDistEver = 0.0;
        for (var step = 0; step < 600; step++)
        {
            director.Tick();

            // Containment invariant (ORCA wall winding): every pedestrian stays inside the mesh.
            for (var i = 0; i < director.PedestrianCount; i++)
            {
                var p = director.PedestrianPosition(i);
                Assert.True(director.NavMesh.Contains(p),
                    $"pedestrian {i} left the known world at ({p.X:F2},{p.Y:F2}) on step {step}");
                maxPedDistEver = Math.Max(maxPedDistEver, TheIncident.DistanceTo(p.X, p.Y));
            }
        }

        _out.WriteLine($"panicked={director.PanickedCount} converted={director.ConvertedCount} " +
                       $"pedestrians={director.PedestrianCount} escaped={director.EscapedCount} " +
                       $"maxPedDist={maxPedDistEver:F1}");

        Assert.True(director.PanickedCount > 0, "no vehicle ever panicked");
        Assert.True(director.ConvertedCount > 0, "no driver ever abandoned a blocked car");
        Assert.True(director.PedestrianCount > 0, "no pedestrian was ever spawned");
        Assert.True(director.AbandonedCarCount == director.ConvertedCount,
            "every conversion should leave exactly one abandoned-car obstacle");
        // Foot-exodus makes real outward progress (drains toward the safe radius).
        Assert.True(maxPedDistEver >= 0.8 * Config().SafeRadius,
            $"pedestrians made too little outward progress (max {maxPedDistEver:F1} m from incident)");
    }

    // The evac RUN is deterministic (no RNG / wall-clock / order dependence in the evac layer).
    [Fact]
    public void EvacRun_IsDeterministic()
    {
        string Signature()
        {
            var (_, d, _) = Build();
            for (var step = 0; step < 300; step++)
            {
                d.Tick();
            }

            // Fold the whole observable end-state into a string: counts + every pedestrian pose.
            var sb = new System.Text.StringBuilder();
            sb.Append(d.PanickedCount).Append('|').Append(d.ConvertedCount).Append('|')
              .Append(d.PedestrianCount).Append('|').Append(d.EscapedCount).Append(';');
            for (var i = 0; i < d.PedestrianCount; i++)
            {
                var p = d.PedestrianPosition(i);
                sb.Append(p.X.ToString("R")).Append(',').Append(p.Y.ToString("R"))
                  .Append(d.PedestrianEscaped(i) ? 'E' : 'f').Append(';');
            }

            return sb.ToString();
        }

        Assert.Equal(Signature(), Signature());
    }

    // Sanity: with the incident set far in the future so it never fires, NOTHING panics/converts and no
    // pedestrian is ever created — the evac layer is inert and the run is just organized traffic.
    [Fact]
    public void NoIncident_LayerIsInert()
    {
        var engine = new Engine();
        engine.LoadNetwork(NetPath);
        var vtype = engine.DefineVType(new VTypeParams { VClass = "passenger", Sigma = 0.0 });
        var net = Sim.Ingest.NetworkParser.Parse(NetPath);
        var cfg = Config();
        var neverFires = new Incident(X: 180.0, Y: 180.0, StartTime: 1e9, Radius: 140.0);
        var director = new EvacDirector(engine, net, neverFires, cfg, StepLength);

        foreach (var (from, to) in Routes)
        {
            director.Track(engine.SpawnVehicle(vtype, from, to, departPos: 5.0));
        }

        for (var step = 0; step < 200; step++)
        {
            director.Tick();
        }

        Assert.Equal(0, director.PanickedCount);
        Assert.Equal(0, director.ConvertedCount);
        Assert.Equal(0, director.PedestrianCount);
    }

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Traffic.sln")))
        {
            dir = dir.Parent;
        }

        return dir?.FullName
            ?? throw new InvalidOperationException("Could not locate repo root (Traffic.sln not found above test assembly).");
    }
}
